import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'pt-BR' | 'es';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Dashboard
    'dashboard.title': 'NPS Campaigns',
    'dashboard.subtitle': 'Monitor and manage your NPS campaigns',
    'dashboard.newCampaign': 'New Campaign',
    'dashboard.noCampaigns': 'No campaigns yet',
    'dashboard.noCampaignsDesc': 'Create your first NPS campaign to start collecting customer feedback.',
    'dashboard.createCampaign': 'Create Campaign',
    
    // Campaign
    'campaign.active': 'Active',
    'campaign.inactive': 'Inactive',
    'campaign.dashboard': 'Dashboard',
    'campaign.edit': 'Edit',
    'campaign.responses': 'View Responses',
    'campaign.editForm': 'Edit Form',
    'campaign.share': 'Share Survey',
    'campaign.noResponses': 'No responses yet',
    'campaign.noResponsesDesc': 'Share your NPS survey with customers to start collecting feedback.',
    'campaign.currentNps': 'Current NPS Score',
    'campaign.npsTrend': 'NPS Trend',
    'campaign.responseDistribution': 'Response Distribution',
    'campaign.latestResponses': 'Latest Responses',
    'campaign.detractors': 'Detractors',
    'campaign.passives': 'Passives',
    'campaign.promoters': 'Promoters',
    'campaign.viewAll': 'View All',
    
    // Settings
    'settings.title': 'Settings',
    'settings.appConfig': 'App Configuration',
    'settings.dataManagement': 'Data Management',
    'settings.themeColor': 'Theme Color',
    'settings.logoUrl': 'Logo URL (Optional)',
    'settings.defaultEmail': 'Default Email',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.sources': 'Sources',
    'settings.situations': 'Situations',
    'settings.groups': 'Groups',
    'settings.sourcesDesc': 'Manage sources where customer feedback comes from',
    'settings.situationsDesc': 'Manage possible statuses for NPS responses',
    'settings.groupsDesc': 'Manage customer groups for segmentation',
    'settings.saveSettings': 'Save Settings',
    'settings.saved': 'Settings saved successfully',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.back': 'Back',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.color': 'Color',
    'common.actions': 'Actions',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.confirm': 'Confirm',
    'common.warning': 'Warning',
    'common.close': 'Close',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.test': 'Test',
    'common.enable': 'Enable',
    'common.disable': 'Disable',
    'common.configuration': 'Configuration',
    'common.general': 'General',
    'common.advanced': 'Advanced',
    'common.preview': 'Preview',
    'common.refresh': 'Refresh',
    
    // Login
    'login.title': 'NPS Master',
    'login.subtitle': 'Sign in to your account',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.signIn': 'Sign in',
    'login.demo': 'For demo purposes, enter any email and password',
    
    // Survey
    'survey.notFound': 'Survey Not Found',
    'survey.notFoundDesc': 'This survey may have been removed or is no longer active.',
    'survey.thankYou': 'Thank You!',
    'survey.submitted': 'Your feedback has been submitted successfully. We appreciate your input!',
    'survey.notLikely': 'Not likely at all',
    'survey.extremelyLikely': 'Extremely likely',
    'survey.submitFeedback': 'Submit Feedback',
    
    // Overview
    'overview.title': 'General Dashboard',
    'overview.subtitle': 'Overview of all NPS campaigns',
    'overview.totalCampaigns': 'Total Campaigns',
    'overview.averageNps': 'Average NPS',
    'overview.totalResponses': 'Total Responses',
    'overview.promoters': 'Promoters',
    'overview.activeCampaigns': 'active',
    'overview.allCampaigns': 'All campaigns',
    'overview.responses': 'responses',
    'overview.ofTotal': 'of total',
    'overview.generalNps': 'General NPS',
    'overview.generalDistribution': 'General Distribution',
    'overview.activeCampaignsTitle': 'Active Campaigns',
    'overview.viewAll': 'View All',
    'overview.noCampaigns': 'No campaigns found',
    'overview.noCampaignsDesc': 'Create your first NPS campaign to start collecting feedback.',
    'overview.createFirstCampaign': 'Create First Campaign',
    'overview.basedOn': 'Based on',
    'overview.campaignsText': 'campaigns',
    'overview.growing': 'Growing',
    'overview.declining': 'Declining',
    'overview.stable': 'Stable',
    'overview.active': 'Active',
    'overview.inactive': 'Inactive',
    'overview.view': 'View',
    'overview.viewAllCampaigns': 'View all',
    
    // Reports
    'reports.title': 'NPS Reports',
    'reports.subtitle': 'Detailed analysis of NPS campaign performance',
    'reports.update': 'Update',
    'reports.exportReport': 'Export Report',
    'reports.campaigns': 'Campaigns',
    'reports.period': 'Period',
    'reports.filtersApplied': 'Applied Filters',
    'reports.applyFilters': 'Apply Filters',
    'reports.clearFilters': 'Clear Filters',
    'reports.last7Days': 'Last 7 days',
    'reports.last30Days': 'Last 30 days',
    'reports.last90Days': 'Last 90 days',
    'reports.lastYear': 'Last year',
    'reports.selectCampaigns': 'Select campaigns to generate report',
    'reports.selectCampaignsDesc': 'Choose one or more campaigns in the filters above to view NPS data.',
    'reports.npsTrend': 'NPS Trend',
    'reports.responseDistribution': 'Response Distribution',
    'reports.responsesBySource': 'Responses by Source',
    'reports.campaignComparison': 'Campaign Comparison',
    'reports.responsesByDay': 'Responses by Day',
    'reports.scoreDistribution': 'Score Distribution',
    'reports.campaign': 'Campaign',
    'reports.responses': 'Responses',
    'reports.nps': 'NPS',
    'reports.neutrals': 'Neutrals',
    'reports.detractors': 'Detractors',
    'reports.insufficientData': 'Insufficient data to show trend',
    'reports.collectMoreData': 'Collect more responses over time',
    'reports.dailyResponseVolume': 'Daily Response Volume',
    'reports.responsesByScore': 'Number of Responses by Score',
    'reports.npsOverTime': 'NPS Over Time',
    
    // Contacts
    'contacts.title': 'Contacts',
    'contacts.subtitle': 'Manage your contacts and organize by groups',
    'contacts.importExcel': 'Import Excel',
    'contacts.export': 'Export',
    'contacts.newContact': 'New Contact',
    'contacts.search': 'Search by name, email, phone or company...',
    'contacts.filters': 'Filters',
    'contacts.filterByGroup': 'Filter by Group',
    'contacts.filterByTags': 'Filter by Tags',
    'contacts.allGroups': 'All groups',
    'contacts.totalContacts': 'Total Contacts',
    'contacts.filteredContacts': 'Filtered Contacts',
    'contacts.activeGroups': 'Active Groups',
    'contacts.uniqueTags': 'Unique Tags',
    'contacts.withCompany': 'With Company',
    'contacts.noContacts': 'No contacts yet',
    'contacts.noContactsDesc': 'Add your first contact to start organizing your network.',
    'contacts.noContactsFound': 'No contacts found',
    'contacts.noContactsFoundDesc': 'Try adjusting the filters to find the contacts you are looking for.',
    'contacts.addFirstContact': 'Add First Contact',
    'contacts.editContact': 'Edit Contact',
    'contacts.newContactTitle': 'New Contact',
    'contacts.name': 'Name',
    'contacts.email': 'Email',
    'contacts.phone': 'Phone',
    'contacts.company': 'Company',
    'contacts.position': 'Position',
    'contacts.groups': 'Groups',
    'contacts.tags': 'Tags',
    'contacts.notes': 'Notes',
    'contacts.addTag': 'Add tag...',
    'contacts.add': 'Add',
    'contacts.addNotesPlaceholder': 'Add notes about this contact...',
    'contacts.createdOn': 'Created on',
    'contacts.showing': 'Showing',
    'contacts.to': 'to',
    'contacts.of': 'of',
    'contacts.contactsText': 'contacts',
    'contacts.previous': 'Previous',
    'contacts.next': 'Next',
    'contacts.importContacts': 'Import Contacts from Excel',
    'contacts.downloadTemplate': 'Download Template',
    'contacts.importInstructions': 'Import Instructions',
    'contacts.csvFormat': 'File must be in CSV format (comma separated)',
    'contacts.acceptedColumns': 'Accepted columns: Name, Email, Phone, Company, Position, Tags, Notes',
    'contacts.requiredFields': 'Name, Email and Phone are required',
    'contacts.tagsSeparator': 'Tags must be separated by semicolon (;)',
    'contacts.downloadTemplateDesc': 'Download the template to see the correct format',
    'contacts.selectCsvFile': 'Select CSV File',
    'contacts.clickToSelect': 'Click to select a CSV file or drag here',
    'contacts.fileSelected': 'File selected:',
    'contacts.importError': 'Import Error',
    'contacts.importCompleted': 'Import Completed',
    'contacts.processing': 'Processing...',
    'contacts.importingContacts': 'Importing contacts, please wait...',
    'contacts.preview': 'Preview (first 5 rows)',
    'contacts.importContactsButton': 'Import Contacts',
    
    // Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your personal information and preferences',
    'profile.editProfile': 'Edit Profile',
    'profile.saveChanges': 'Save Changes',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.phone': 'Phone',
    'profile.company': 'Company',
    'profile.position': 'Position',
    'profile.memberSince': 'Member since',
    'profile.passwordSecurity': 'Password and Security',
    'profile.changePassword': 'Change Password',
    'profile.changePasswordDesc': 'Update your password to keep your account secure',
    'profile.exportData': 'Export My Data',
    'profile.exportDataDesc': 'Download a copy of all your personal data',
    'profile.deleteAccount': 'Delete My Account',
    'profile.deleteAccountDesc': 'Permanently delete your account and all your data',
    'profile.privacyProtection': 'Privacy and Data Protection',
    'profile.lgpdGdpr': 'LGPD and GDPR',
    'profile.complianceDesc': 'We comply with Brazil\'s General Data Protection Law (LGPD) and the European Union\'s General Data Protection Regulation (GDPR).',
    'profile.privacyRights': 'Your Privacy Rights',
    'profile.marketingConsent': 'I accept to receive marketing communications and news',
    'profile.analyticsConsent': 'I accept the use of data for analysis and service improvements',
    'profile.thirdPartyConsent': 'I accept data sharing with trusted partners',
    'profile.yourRights': 'Your Rights',
    'profile.rightAccess': 'Right to access your personal data',
    'profile.rightCorrection': 'Right to correct incorrect data',
    'profile.rightErasure': 'Right to be forgotten (data deletion)',
    'profile.rightPortability': 'Right to data portability',
    'profile.rightWithdraw': 'Right to withdraw consent at any time',
    'profile.accountInfo': 'Account Information',
    'profile.status': 'Status',
    'profile.plan': 'Plan',
    'profile.lastUpdate': 'Last update',
    'profile.preferences': 'Preferences',
    'profile.preferredLanguage': 'Preferred Language',
    'profile.interfaceTheme': 'Interface Theme',
    'profile.darkMode': 'Dark Mode',
    'profile.lightMode': 'Light Mode',
    'profile.toggleTheme': 'Toggle Theme',
    'profile.emailNotifications': 'Email Notifications',
    'profile.newNpsResponses': 'New NPS responses',
    'profile.weeklyReports': 'Weekly reports',
    'profile.productUpdates': 'Product updates',
    'profile.avatarTip': 'Avatar Tip',
    'profile.avatarTipDesc': 'Use a square image of at least 200x200px for better quality.',
    'profile.active': 'Active',
    'profile.professional': 'Professional',
    
    // Settings
    'settings.generalSettings': 'General Settings',
    'settings.themeColorLabel': 'Theme Color',
    'settings.companyData': 'Company Data',
    'settings.companyName': 'Company Name',
    'settings.document': 'Document (CNPJ/CPF)',
    'settings.address': 'Address',
    'settings.emailSettings': 'Email Settings',
    'settings.smsWhatsappSettings': 'SMS and WhatsApp Settings',
    'settings.smtp': 'SMTP',
    'settings.zenviaEmail': 'ZenVia Email',
    'settings.zenviaSms': 'ZenVia SMS',
    'settings.zenviaWhatsapp': 'ZenVia WhatsApp',
    'settings.testConnection': 'Test Connection',
    'settings.smtpServer': 'SMTP Server',
    'settings.port': 'Port',
    'settings.username': 'Username',
    'settings.password': 'Password',
    'settings.senderName': 'Sender Name',
    'settings.senderEmail': 'Sender Email',
    'settings.apiKey': 'API Key',
    'settings.senderNumber': 'Sender Number',
    'settings.fromNumber': 'From Number',
    'settings.testEmailSent': 'Test email sent successfully!',
    'settings.testEmailError': 'Error sending test email',
    'settings.testApiSuccess': 'API tested successfully!',
    'settings.testApiError': 'Error testing API',
    'settings.emailTestSent': 'Test Email Sent',
    'settings.emailTestError': 'Error Sending Email',
    'settings.zenviaTestSent': 'ZenVia Test Message Sent',
    'settings.zenviaTestError': 'Error Sending Test Message',
    'settings.troubleshootingTips': 'Troubleshooting tips:',
    'settings.checkCredentials': 'Check if credentials are correct',
    'settings.checkConfiguration': 'Check if configuration is correct',
    'settings.checkService': 'Check if service is active in your account',
    'settings.phoneRequired': 'Phone number required in profile',
    'settings.domainConfiguration': 'Check if domain is configured',
    
    // Entity CRUD
    'entity.list': 'List',
    'entity.noItemsFound': 'No items found',
    'entity.addFirstItem': 'Click the button above to add your first item.',
    'entity.deleteConfirm': 'Are you sure you want to delete this item?',
    'entity.deleteError': 'Error deleting. Please try again.',
    'entity.saveError': 'Error saving. Please try again.',
    'entity.nameRequired': 'Name is required',
    'entity.noColor': 'No color',
    'entity.enterDescription': 'Enter a description',
    
    // Dashboard/Campaigns
    'campaigns.title': 'NPS Campaigns',
    'campaigns.subtitle': 'Monitor and manage your NPS campaigns',
    'campaigns.newCampaign': 'New Campaign',
    'campaigns.noCampaigns': 'No campaigns yet',
    'campaigns.noCampaignsDesc': 'Create your first NPS campaign to start collecting customer feedback.',
    'campaigns.createCampaign': 'Create Campaign',
    'campaigns.total': 'total',
    'campaigns.campaign': 'campaign',
    'campaigns.campaigns': 'campaigns',
    'campaigns.editCampaign': 'Edit campaign',
    'campaigns.deleteCampaign': 'Delete campaign',
    'campaigns.deleteConfirm': 'This action cannot be undone',
    'campaigns.deleteDescription': 'This will permanently delete the campaign and all associated data.',
    'campaigns.campaignName': 'Campaign Name',
    'campaigns.responses': 'responses',
    'campaigns.response': 'response',
    'campaigns.created': 'Created',
    'campaigns.whatWillBeDeleted': 'What will be deleted:',
    'campaigns.campaignConfig': 'Campaign configuration and settings',
    'campaigns.allResponses': 'All survey responses',
    'campaigns.customFields': 'Custom form fields and design',
    'campaigns.surveyCustomization': 'Survey customization (colors, images, logo)',
    'campaigns.analyticsData': 'All analytics and reports data',
    'campaigns.deleteWarning': 'Are you sure you want to delete',
    'campaigns.actionCannotBeUndone': 'This action cannot be undone and all data will be permanently lost.',
    'campaigns.deleteCampaignButton': 'Delete Campaign',
    
    // Common additional
    'common.created': 'Created on',
    'common.total': 'Total',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel de Control',
    'nav.settings': 'Configuraciones',
    'nav.logout': 'Cerrar Sesión',
    
    // Dashboard
    'dashboard.title': 'Campañas NPS',
    'dashboard.subtitle': 'Monitorea y gestiona tus campañas NPS',
    'dashboard.newCampaign': 'Nueva Campaña',
    'dashboard.noCampaigns': 'Aún no hay campañas',
    'dashboard.noCampaignsDesc': 'Crea tu primera campaña NPS para comenzar a recopilar comentarios de clientes.',
    'dashboard.createCampaign': 'Crear Campaña',
    
    // Campaign
    'campaign.active': 'Activa',
    'campaign.inactive': 'Inactiva',
    'campaign.dashboard': 'Panel de Control',
    'campaign.edit': 'Editar',
    'campaign.responses': 'Ver Respuestas',
    'campaign.editForm': 'Editar Formulario',
    'campaign.share': 'Compartir Encuesta',
    'campaign.noResponses': 'Aún no hay respuestas',
    'campaign.noResponsesDesc': 'Comparte tu encuesta NPS con clientes para comenzar a recopilar comentarios.',
    'campaign.currentNps': 'Puntuación NPS Actual',
    'campaign.npsTrend': 'Tendencia NPS',
    'campaign.responseDistribution': 'Distribución de Respuestas',
    'campaign.latestResponses': 'Últimas Respuestas',
    'campaign.detractors': 'Detractores',
    'campaign.passives': 'Neutrales',
    'campaign.promoters': 'Promotores',
    'campaign.viewAll': 'Ver Todos',
    
    // Settings
    'settings.title': 'Configuraciones',
    'settings.appConfig': 'Configuración de la App',
    'settings.dataManagement': 'Gestión de Datos',
    'settings.themeColor': 'Color del Tema',
    'settings.logoUrl': 'URL del Logo (Opcional)',
    'settings.defaultEmail': 'Email Predeterminado',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.light': 'Claro',
    'settings.dark': 'Oscuro',
    'settings.sources': 'Fuentes',
    'settings.situations': 'Situaciones',
    'settings.groups': 'Grupos',
    'settings.sourcesDesc': 'Gestiona las fuentes de donde provienen los comentarios de clientes',
    'settings.situationsDesc': 'Gestiona los posibles estados para respuestas NPS',
    'settings.groupsDesc': 'Gestiona grupos de clientes para segmentación',
    'settings.saveSettings': 'Guardar Configuraciones',
    'settings.saved': 'Configuraciones guardadas exitosamente',
    'settings.generalSettings': 'Configuraciones Generales',
    'settings.themeColorLabel': 'Color del Tema',
    'settings.companyData': 'Datos de la Empresa',
    'settings.companyName': 'Nombre de la Empresa',
    'settings.document': 'Documento (CNPJ/CPF)',
    'settings.address': 'Dirección',
    'settings.emailSettings': 'Configuraciones de Email',
    'settings.smsWhatsappSettings': 'Configuraciones de SMS y WhatsApp',
    'settings.smtp': 'SMTP',
    'settings.zenviaEmail': 'ZenVia Email',
    'settings.zenviaSms': 'ZenVia SMS',
    'settings.zenviaWhatsapp': 'ZenVia WhatsApp',
    'settings.testConnection': 'Probar Conexión',
    'settings.smtpServer': 'Servidor SMTP',
    'settings.port': 'Puerto',
    'settings.username': 'Usuario',
    'settings.password': 'Contraseña',
    'settings.senderName': 'Nombre del Remitente',
    'settings.senderEmail': 'Email del Remitente',
    'settings.apiKey': 'Clave API',
    'settings.senderNumber': 'Número del Remitente',
    'settings.fromNumber': 'Número del Remitente',
    'settings.testEmailSent': '¡Email de prueba enviado exitosamente!',
    'settings.testEmailError': 'Error al enviar email de prueba',
    'settings.testApiSuccess': '¡API probada exitosamente!',
    'settings.testApiError': 'Error al probar API',
    'settings.emailTestSent': 'Email de Prueba Enviado',
    'settings.emailTestError': 'Error al Enviar Email',
    'settings.zenviaTestSent': 'Mensaje de Prueba ZenVia Enviado',
    'settings.zenviaTestError': 'Error al Enviar Mensaje de Prueba',
    'settings.troubleshootingTips': 'Consejos para resolver problemas:',
    'settings.checkCredentials': 'Verifica si las credenciales son correctas',
    'settings.checkConfiguration': 'Verifica si la configuración es correcta',
    'settings.checkService': 'Verifica si el servicio está activo en tu cuenta',
    'settings.phoneRequired': 'Número de teléfono requerido en el perfil',
    'settings.domainConfiguration': 'Verifica si el dominio está configurado',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.add': 'Agregar',
    'common.back': 'Volver',
    'common.name': 'Nombre',
    'common.description': 'Descripción',
    'common.color': 'Color',
    'common.actions': 'Acciones',
    'common.required': 'Requerido',
    'common.optional': 'Opcional',
    'common.confirm': 'Confirmar',
    'common.warning': 'Advertencia',
    'common.close': 'Cerrar',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.retry': 'Reintentar',
    'common.test': 'Probar',
    'common.enable': 'Activar',
    'common.disable': 'Desactivar',
    'common.configuration': 'Configuración',
    'common.general': 'General',
    'common.advanced': 'Avanzado',
    'common.preview': 'Vista Previa',
    'common.refresh': 'Actualizar',
    'common.created': 'Creado el',
    'common.total': 'Total',
    
    // Login
    'login.title': 'NPS Master',
    'login.subtitle': 'Inicia sesión en tu cuenta',
    'login.email': 'Dirección de Email',
    'login.password': 'Contraseña',
    'login.signIn': 'Iniciar Sesión',
    'login.demo': 'Para demostración, ingresa cualquier email y contraseña',
    
    // Survey
    'survey.notFound': 'Encuesta No Encontrada',
    'survey.notFoundDesc': 'Esta encuesta puede haber sido eliminada o ya no está activa.',
    'survey.thankYou': '¡Gracias!',
    'survey.submitted': 'Tu comentario ha sido enviado exitosamente. ¡Apreciamos tu aporte!',
    'survey.notLikely': 'Nada probable',
    'survey.extremelyLikely': 'Extremadamente probable',
    'survey.submitFeedback': 'Enviar Comentario',
    
    // Overview
    'overview.title': 'Panel General',
    'overview.subtitle': 'Resumen de todas las campañas NPS',
    'overview.totalCampaigns': 'Total de Campañas',
    'overview.averageNps': 'NPS Promedio',
    'overview.totalResponses': 'Total de Respuestas',
    'overview.promoters': 'Promotores',
    'overview.activeCampaigns': 'activas',
    'overview.allCampaigns': 'Todas las campañas',
    'overview.responses': 'respuestas',
    'overview.ofTotal': 'del total',
    'overview.generalNps': 'NPS General',
    'overview.generalDistribution': 'Distribución General',
    'overview.activeCampaignsTitle': 'Campañas Activas',
    'overview.viewAll': 'Ver Todas',
    'overview.noCampaigns': 'No se encontraron campañas',
    'overview.noCampaignsDesc': 'Crea tu primera campaña NPS para comenzar a recopilar comentarios.',
    'overview.createFirstCampaign': 'Crear Primera Campaña',
    'overview.basedOn': 'Basado en',
    'overview.campaignsText': 'campañas',
    'overview.growing': 'Creciendo',
    'overview.declining': 'Declinando',
    'overview.stable': 'Estable',
    'overview.active': 'Activa',
    'overview.inactive': 'Inactiva',
    'overview.view': 'Ver',
    'overview.viewAllCampaigns': 'Ver todas las',
    
    // Reports
    'reports.title': 'Reportes NPS',
    'reports.subtitle': 'Análisis detallado del rendimiento de campañas NPS',
    'reports.update': 'Actualizar',
    'reports.exportReport': 'Exportar Reporte',
    'reports.campaigns': 'Campañas',
    'reports.period': 'Período',
    'reports.filtersApplied': 'Filtros Aplicados',
    'reports.applyFilters': 'Aplicar Filtros',
    'reports.clearFilters': 'Limpiar Filtros',
    'reports.last7Days': 'Últimos 7 días',
    'reports.last30Days': 'Últimos 30 días',
    'reports.last90Days': 'Últimos 90 días',
    'reports.lastYear': 'Último año',
    'reports.selectCampaigns': 'Selecciona campañas para generar reporte',
    'reports.selectCampaignsDesc': 'Elige una o más campañas en los filtros arriba para ver datos de NPS.',
    'reports.npsTrend': 'Tendencia NPS',
    'reports.responseDistribution': 'Distribución de Respuestas',
    'reports.responsesBySource': 'Respuestas por Fuente',
    'reports.campaignComparison': 'Comparación de Campañas',
    'reports.responsesByDay': 'Respuestas por Día',
    'reports.scoreDistribution': 'Distribución por Puntuación',
    'reports.campaign': 'Campaña',
    'reports.responses': 'Respuestas',
    'reports.nps': 'NPS',
    'reports.neutrals': 'Neutrales',
    'reports.detractors': 'Detractores',
    'reports.insufficientData': 'Datos insuficientes para mostrar tendencia',
    'reports.collectMoreData': 'Recopila más respuestas a lo largo del tiempo',
    'reports.dailyResponseVolume': 'Volumen de Respuestas Diarias',
    'reports.responsesByScore': 'Número de Respuestas por Puntuación',
    'reports.npsOverTime': 'NPS a lo Largo del Tiempo',
    
    // Contacts
    'contacts.title': 'Contactos',
    'contacts.subtitle': 'Gestiona tus contactos y organiza por grupos',
    'contacts.importExcel': 'Importar Excel',
    'contacts.export': 'Exportar',
    'contacts.newContact': 'Nuevo Contacto',
    'contacts.search': 'Buscar por nombre, email, teléfono o empresa...',
    'contacts.filters': 'Filtros',
    'contacts.filterByGroup': 'Filtrar por Grupo',
    'contacts.filterByTags': 'Filtrar por Etiquetas',
    'contacts.allGroups': 'Todos los grupos',
    'contacts.totalContacts': 'Total de Contactos',
    'contacts.filteredContacts': 'Contactos Filtrados',
    'contacts.activeGroups': 'Grupos Activos',
    'contacts.uniqueTags': 'Etiquetas Únicas',
    'contacts.withCompany': 'Con Empresa',
    'contacts.noContacts': 'Aún no hay contactos',
    'contacts.noContactsDesc': 'Agrega tu primer contacto para comenzar a organizar tu red.',
    'contacts.noContactsFound': 'No se encontraron contactos',
    'contacts.noContactsFoundDesc': 'Intenta ajustar los filtros para encontrar los contactos que buscas.',
    'contacts.addFirstContact': 'Agregar Primer Contacto',
    'contacts.editContact': 'Editar Contacto',
    'contacts.newContactTitle': 'Nuevo Contacto',
    'contacts.name': 'Nombre',
    'contacts.email': 'Email',
    'contacts.phone': 'Teléfono',
    'contacts.company': 'Empresa',
    'contacts.position': 'Cargo',
    'contacts.groups': 'Grupos',
    'contacts.tags': 'Etiquetas',
    'contacts.notes': 'Notas',
    'contacts.addTag': 'Agregar etiqueta...',
    'contacts.add': 'Agregar',
    'contacts.addNotesPlaceholder': 'Agregar notas sobre este contacto...',
    'contacts.createdOn': 'Creado el',
    'contacts.showing': 'Mostrando',
    'contacts.to': 'a',
    'contacts.of': 'de',
    'contacts.contactsText': 'contactos',
    'contacts.previous': 'Anterior',
    'contacts.next': 'Siguiente',
    'contacts.importContacts': 'Importar Contactos desde Excel',
    'contacts.downloadTemplate': 'Descargar Plantilla',
    'contacts.importInstructions': 'Instrucciones de Importación',
    'contacts.csvFormat': 'El archivo debe estar en formato CSV (separado por comas)',
    'contacts.acceptedColumns': 'Columnas aceptadas: Nombre, Email, Teléfono, Empresa, Cargo, Etiquetas, Notas',
    'contacts.requiredFields': 'Nombre, Email y Teléfono son requeridos',
    'contacts.tagsSeparator': 'Las etiquetas deben estar separadas por punto y coma (;)',
    'contacts.downloadTemplateDesc': 'Descarga la plantilla para ver el formato correcto',
    'contacts.selectCsvFile': 'Seleccionar Archivo CSV',
    'contacts.clickToSelect': 'Haz clic para seleccionar un archivo CSV o arrastra aquí',
    'contacts.fileSelected': 'Archivo seleccionado:',
    'contacts.importError': 'Error de Importación',
    'contacts.importCompleted': 'Importación Completada',
    'contacts.processing': 'Procesando...',
    'contacts.importingContacts': 'Importando contactos, por favor espera...',
    'contacts.preview': 'Vista previa (primeras 5 filas)',
    'contacts.importContactsButton': 'Importar Contactos',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.subtitle': 'Gestiona tu información personal y preferencias',
    'profile.editProfile': 'Editar Perfil',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.personalInfo': 'Información Personal',
    'profile.fullName': 'Nombre Completo',
    'profile.phone': 'Teléfono',
    'profile.company': 'Empresa',
    'profile.position': 'Cargo',
    'profile.memberSince': 'Miembro desde',
    'profile.passwordSecurity': 'Contraseña y Seguridad',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.changePasswordDesc': 'Actualiza tu contraseña para mantener tu cuenta segura',
    'profile.exportData': 'Exportar Mis Datos',
    'profile.exportDataDesc': 'Descarga una copia de todos tus datos personales',
    'profile.deleteAccount': 'Eliminar Mi Cuenta',
    'profile.deleteAccountDesc': 'Elimina permanentemente tu cuenta y todos tus datos',
    'profile.privacyProtection': 'Privacidad y Protección de Datos',
    'profile.lgpdGdpr': 'LGPD y GDPR',
    'profile.complianceDesc': 'Cumplimos con la Ley General de Protección de Datos (LGPD) de Brasil y el Reglamento General de Protección de Datos (GDPR) de la Unión Europea.',
    'profile.privacyRights': 'Tus Derechos de Privacidad',
    'profile.marketingConsent': 'Acepto recibir comunicaciones de marketing y noticias',
    'profile.analyticsConsent': 'Acepto el uso de datos para análisis y mejoras del servicio',
    'profile.thirdPartyConsent': 'Acepto el intercambio de datos con socios de confianza',
    'profile.yourRights': 'Tus Derechos',
    'profile.rightAccess': 'Derecho a acceder a tus datos personales',
    'profile.rightCorrection': 'Derecho a corregir datos incorrectos',
    'profile.rightErasure': 'Derecho al olvido (eliminación de datos)',
    'profile.rightPortability': 'Derecho a la portabilidad de datos',
    'profile.rightWithdraw': 'Derecho a retirar el consentimiento en cualquier momento',
    'profile.accountInfo': 'Información de la Cuenta',
    'profile.status': 'Estado',
    'profile.plan': 'Plan',
    'profile.lastUpdate': 'Última actualización',
    'profile.preferences': 'Preferencias',
    'profile.preferredLanguage': 'Idioma Preferido',
    'profile.interfaceTheme': 'Tema de la Interfaz',
    'profile.darkMode': 'Modo Oscuro',
    'profile.lightMode': 'Modo Claro',
    'profile.toggleTheme': 'Cambiar Tema',
    'profile.emailNotifications': 'Notificaciones por Email',
    'profile.newNpsResponses': 'Nuevas respuestas NPS',
    'profile.weeklyReports': 'Reportes semanales',
    'profile.productUpdates': 'Actualizaciones del producto',
    'profile.avatarTip': 'Consejo para Avatar',
    'profile.avatarTipDesc': 'Usa una imagen cuadrada de al menos 200x200px para mejor calidad.',
    'profile.active': 'Activo',
    'profile.professional': 'Profesional',
    
    // Entity CRUD
    'entity.list': 'Lista',
    'entity.noItemsFound': 'No se encontraron elementos',
    'entity.addFirstItem': 'Haz clic en el botón de arriba para agregar tu primer elemento.',
    'entity.deleteConfirm': '¿Estás seguro de que quieres eliminar este elemento?',
    'entity.deleteError': 'Error al eliminar. Inténtalo de nuevo.',
    'entity.saveError': 'Error al guardar. Inténtalo de nuevo.',
    'entity.nameRequired': 'El nombre es requerido',
    'entity.noColor': 'Sin color',
    'entity.enterDescription': 'Ingresa una descripción',
    
    // Dashboard/Campaigns
    'campaigns.title': 'Campañas NPS',
    'campaigns.subtitle': 'Monitorea y gestiona tus campañas NPS',
    'campaigns.newCampaign': 'Nueva Campaña',
    'campaigns.noCampaigns': 'Aún no hay campañas',
    'campaigns.noCampaignsDesc': 'Crea tu primera campaña NPS para comenzar a recopilar comentarios de clientes.',
    'campaigns.createCampaign': 'Crear Campaña',
    'campaigns.total': 'en total',
    'campaigns.campaign': 'campaña',
    'campaigns.campaigns': 'campañas',
    'campaigns.editCampaign': 'Editar campaña',
    'campaigns.deleteCampaign': 'Eliminar campaña',
    'campaigns.deleteConfirm': 'Esta acción no se puede deshacer',
    'campaigns.deleteDescription': 'Esto eliminará permanentemente la campaña y todos los datos asociados.',
    'campaigns.campaignName': 'Nombre de la Campaña',
    'campaigns.responses': 'respuestas',
    'campaigns.response': 'respuesta',
    'campaigns.created': 'Creada',
    'campaigns.whatWillBeDeleted': 'Lo que será eliminado:',
    'campaigns.campaignConfig': 'Configuración y ajustes de la campaña',
    'campaigns.allResponses': 'Todas las respuestas de la encuesta',
    'campaigns.customFields': 'Campos personalizados del formulario y diseño',
    'campaigns.surveyCustomization': 'Personalización de la encuesta (colores, imágenes, logo)',
    'campaigns.analyticsData': 'Todos los datos de análisis y reportes',
    'campaigns.deleteWarning': '¿Estás seguro de que quieres eliminar',
    'campaigns.actionCannotBeUndone': 'Esta acción no se puede deshacer y todos los datos se perderán permanentemente.',
    'campaigns.deleteCampaignButton': 'Eliminar Campaña',
    
    // Settings specific
    'settings.integrationStatus': 'Estado de Integración',
    'settings.enabled': 'Habilitado',
    'settings.disabled': 'Deshabilitado',
    'settings.notConfigured': 'No Configurado',
    'settings.testSuccessful': 'Prueba Exitosa',
    'settings.testFailed': 'Prueba Fallida',
    'settings.configurationRequired': 'Configuración Requerida',
    'settings.fillAllFields': 'Por favor, completa todos los campos requeridos',
    'settings.testingConnection': 'Probando conexión...',
    'settings.connectionSuccessful': 'Conexión exitosa',
    'settings.connectionFailed': 'Conexión fallida',
    'settings.saveFirst': 'Guarda la configuración primero',
    'settings.testAfterSave': 'Prueba la conexión después de guardar',
  },
  'pt-BR': {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',
    
    // Dashboard
    'dashboard.title': 'Campanhas NPS',
    'dashboard.subtitle': 'Monitore e gerencie suas campanhas NPS',
    'dashboard.newCampaign': 'Nova Campanha',
    'dashboard.noCampaigns': 'Nenhuma campanha ainda',
    'dashboard.noCampaignsDesc': 'Crie sua primeira campanha NPS para começar a coletar feedback dos clientes.',
    'dashboard.createCampaign': 'Criar Campanha',
    
    // Campaign
    'campaign.active': 'Ativa',
    'campaign.inactive': 'Inativa',
    'campaign.dashboard': 'Dashboard',
    'campaign.edit': 'Editar',
    'campaign.responses': 'Ver Respostas',
    'campaign.editForm': 'Editar Formulário',
    'campaign.share': 'Compartilhar Pesquisa',
    'campaign.noResponses': 'Nenhuma resposta ainda',
    'campaign.noResponsesDesc': 'Compartilhe sua pesquisa NPS com clientes para começar a coletar feedback.',
    'campaign.currentNps': 'Pontuação NPS Atual',
    'campaign.npsTrend': 'Tendência NPS',
    'campaign.responseDistribution': 'Distribuição de Respostas',
    'campaign.latestResponses': 'Últimas Respostas',
    'campaign.detractors': 'Detratores',
    'campaign.passives': 'Neutros',
    'campaign.promoters': 'Promotores',
    'campaign.viewAll': 'Ver Todos',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.appConfig': 'Configuração do App',
    'settings.dataManagement': 'Gerenciamento de Dados',
    'settings.themeColor': 'Cor do Tema',
    'settings.logoUrl': 'URL do Logo (Opcional)',
    'settings.defaultEmail': 'Email Padrão',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.light': 'Claro',
    'settings.dark': 'Escuro',
    'settings.sources': 'Fontes',
    'settings.situations': 'Situações',
    'settings.groups': 'Grupos',
    'settings.sourcesDesc': 'Gerencie fontes de onde vem o feedback dos clientes',
    'settings.situationsDesc': 'Gerencie possíveis status para respostas NPS',
    'settings.groupsDesc': 'Gerencie grupos de clientes para segmentação',
    'settings.saveSettings': 'Salvar Configurações',
    'settings.saved': 'Configurações salvas com sucesso',
    
    // Common
    'common.loading': 'Carregando...',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.add': 'Adicionar',
    'common.back': 'Voltar',
    'common.name': 'Nome',
    'common.description': 'Descrição',
    'common.color': 'Cor',
    'common.actions': 'Ações',
    'common.required': 'Obrigatório',
    'common.optional': 'Opcional',
    'common.confirm': 'Confirmar',
    'common.warning': 'Aviso',
    'common.close': 'Fechar',
    'common.success': 'Sucesso',
    'common.error': 'Erro',
    'common.retry': 'Tentar Novamente',
    'common.test': 'Testar',
    'common.enable': 'Ativar',
    'common.disable': 'Desativar',
    'common.configuration': 'Configuração',
    'common.general': 'Geral',
    'common.advanced': 'Avançado',
    'common.preview': 'Pré-visualização',
    'common.refresh': 'Atualizar',
    
    // Login
    'login.title': 'NPS Master',
    'login.subtitle': 'Entre na sua conta',
    'login.email': 'Endereço de Email',
    'login.password': 'Senha',
    'login.signIn': 'Entrar',
    'login.demo': 'Para demonstração, digite qualquer email e senha',
    
    // Survey
    'survey.notFound': 'Pesquisa Não Encontrada',
    'survey.notFoundDesc': 'Esta pesquisa pode ter sido removida ou não está mais ativa.',
    'survey.thankYou': 'Obrigado!',
    'survey.submitted': 'Seu feedback foi enviado com sucesso. Agradecemos sua contribuição!',
    'survey.notLikely': 'Nada provável',
    'survey.extremelyLikely': 'Extremamente provável',
    'survey.submitFeedback': 'Enviar Feedback',
    
    // Overview
    'overview.title': 'Dashboard Geral',
    'overview.subtitle': 'Visão geral de todas as campanhas NPS',
    'overview.totalCampaigns': 'Total de Campanhas',
    'overview.averageNps': 'NPS Médio',
    'overview.totalResponses': 'Total de Respostas',
    'overview.promoters': 'Promotores',
    'overview.activeCampaigns': 'ativas',
    'overview.allCampaigns': 'Todas as campanhas',
    'overview.responses': 'respostas',
    'overview.ofTotal': 'do total',
    'overview.generalNps': 'NPS Geral',
    'overview.generalDistribution': 'Distribuição Geral',
    'overview.activeCampaignsTitle': 'Campanhas Ativas',
    'overview.viewAll': 'Ver Todas',
    'overview.noCampaigns': 'Nenhuma campanha encontrada',
    'overview.noCampaignsDesc': 'Crie sua primeira campanha NPS para começar a coletar feedback.',
    'overview.createFirstCampaign': 'Criar Primeira Campanha',
    'overview.basedOn': 'Baseado em',
    'overview.campaignsText': 'campanhas',
    'overview.growing': 'Crescendo',
    'overview.declining': 'Declinando',
    'overview.stable': 'Estável',
    'overview.active': 'Ativa',
    'overview.inactive': 'Inativa',
    'overview.view': 'Ver',
    'overview.viewAllCampaigns': 'Ver todas as',
    
    // Reports
    'reports.title': 'Relatórios NPS',
    'reports.subtitle': 'Análise detalhada do desempenho das campanhas NPS',
    'reports.update': 'Atualizar',
    'reports.exportReport': 'Exportar Relatório',
    'reports.campaigns': 'Campanhas',
    'reports.period': 'Período',
    'reports.filtersApplied': 'Filtros Aplicados',
    'reports.applyFilters': 'Aplicar Filtros',
    'reports.clearFilters': 'Limpar Filtros',
    'reports.last7Days': 'Últimos 7 dias',
    'reports.last30Days': 'Últimos 30 dias',
    'reports.last90Days': 'Últimos 90 dias',
    'reports.lastYear': 'Último ano',
    'reports.selectCampaigns': 'Selecione campanhas para gerar relatório',
    'reports.selectCampaignsDesc': 'Escolha uma ou mais campanhas nos filtros acima para visualizar os dados de NPS.',
    'reports.npsTrend': 'Tendência NPS',
    'reports.responseDistribution': 'Distribuição de Respostas',
    'reports.responsesBySource': 'Respostas por Fonte',
    'reports.campaignComparison': 'Comparação de Campanhas',
    'reports.responsesByDay': 'Respostas por Dia',
    'reports.scoreDistribution': 'Distribuição por Pontuação',
    'reports.campaign': 'Campanha',
    'reports.responses': 'Respostas',
    'reports.nps': 'NPS',
    'reports.neutrals': 'Neutros',
    'reports.detractors': 'Detratores',
    'reports.insufficientData': 'Dados insuficientes para mostrar tendência',
    'reports.collectMoreData': 'Colete mais respostas ao longo do tempo',
    'reports.dailyResponseVolume': 'Volume de Respostas Diárias',
    'reports.responsesByScore': 'Número de Respostas por Pontuação',
    'reports.npsOverTime': 'NPS ao Longo do Tempo',
    
    // Contacts
    'contacts.title': 'Contatos',
    'contacts.subtitle': 'Gerencie seus contatos e organize por grupos',
    'contacts.importExcel': 'Importar Excel',
    'contacts.export': 'Exportar',
    'contacts.newContact': 'Novo Contato',
    'contacts.search': 'Buscar por nome, email, telefone ou empresa...',
    'contacts.filters': 'Filtros',
    'contacts.filterByGroup': 'Filtrar por Grupo',
    'contacts.filterByTags': 'Filtrar por Tags',
    'contacts.allGroups': 'Todos os grupos',
    'contacts.totalContacts': 'Total de Contatos',
    'contacts.filteredContacts': 'Contatos Filtrados',
    'contacts.activeGroups': 'Grupos Ativos',
    'contacts.uniqueTags': 'Tags Únicas',
    'contacts.withCompany': 'Com Empresa',
    'contacts.noContacts': 'Nenhum contato ainda',
    'contacts.noContactsDesc': 'Adicione seu primeiro contato para começar a organizar sua rede.',
    'contacts.noContactsFound': 'Nenhum contato encontrado',
    'contacts.noContactsFoundDesc': 'Tente ajustar os filtros para encontrar os contatos que procura.',
    'contacts.addFirstContact': 'Adicionar Primeiro Contato',
    'contacts.editContact': 'Editar Contato',
    'contacts.newContactTitle': 'Novo Contato',
    'contacts.name': 'Nome',
    'contacts.email': 'Email',
    'contacts.phone': 'Telefone',
    'contacts.company': 'Empresa',
    'contacts.position': 'Cargo',
    'contacts.groups': 'Grupos',
    'contacts.tags': 'Tags',
    'contacts.notes': 'Notas',
    'contacts.addTag': 'Adicionar tag...',
    'contacts.add': 'Adicionar',
    'contacts.addNotesPlaceholder': 'Adicione notas sobre este contato...',
    'contacts.createdOn': 'Criado em',
    'contacts.showing': 'Mostrando',
    'contacts.to': 'a',
    'contacts.of': 'de',
    'contacts.contactsText': 'contatos',
    'contacts.previous': 'Anterior',
    'contacts.next': 'Próxima',
    'contacts.importContacts': 'Importar Contatos do Excel',
    'contacts.downloadTemplate': 'Baixar Template',
    'contacts.importInstructions': 'Instruções para Importação',
    'contacts.csvFormat': 'O arquivo deve estar no formato CSV (separado por vírgulas)',
    'contacts.acceptedColumns': 'Colunas aceitas: Nome, Email, Telefone, Empresa, Cargo, Tags, Notas',
    'contacts.requiredFields': 'Nome, Email e Telefone são obrigatórios',
    'contacts.tagsSeparator': 'Tags devem ser separadas por ponto e vírgula (;)',
    'contacts.downloadTemplateDesc': 'Baixe o template para ver o formato correto',
    'contacts.selectCsvFile': 'Selecionar Arquivo CSV',
    'contacts.clickToSelect': 'Clique para selecionar um arquivo CSV ou arraste aqui',
    'contacts.fileSelected': 'Arquivo selecionado:',
    'contacts.importError': 'Erro na Importação',
    'contacts.importCompleted': 'Importação Concluída',
    'contacts.processing': 'Processando...',
    'contacts.importingContacts': 'Importando contatos, aguarde...',
    'contacts.preview': 'Pré-visualização (primeiras 5 linhas)',
    'contacts.importContactsButton': 'Importar Contatos',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.subtitle': 'Gerencie suas informações pessoais e preferências',
    'profile.editProfile': 'Editar Perfil',
    'profile.saveChanges': 'Salvar Alterações',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.fullName': 'Nome Completo',
    'profile.phone': 'Telefone',
    'profile.company': 'Empresa',
    'profile.position': 'Cargo',
    'profile.memberSince': 'Membro desde',
    'profile.passwordSecurity': 'Senha e Segurança',
    'profile.changePassword': 'Alterar Senha',
    'profile.changePasswordDesc': 'Atualize sua senha para manter sua conta segura',
    'profile.exportData': 'Exportar Meus Dados',
    'profile.exportDataDesc': 'Baixe uma cópia de todos os seus dados pessoais',
    'profile.deleteAccount': 'Excluir Minha Conta',
    'profile.deleteAccountDesc': 'Exclua permanentemente sua conta e todos os seus dados',
    'profile.privacyProtection': 'Privacidade e Proteção de Dados',
    'profile.lgpdGdpr': 'LGPD e GDPR',
    'profile.complianceDesc': 'Estamos em conformidade com a Lei Geral de Proteção de Dados (LGPD) do Brasil e o Regulamento Geral de Proteção de Dados (GDPR) da União Europeia.',
    'profile.privacyRights': 'Seus Direitos de Privacidade',
    'profile.marketingConsent': 'Aceito receber comunicações de marketing e novidades',
    'profile.analyticsConsent': 'Aceito o uso de dados para análises e melhorias do serviço',
    'profile.thirdPartyConsent': 'Aceito o compartilhamento de dados com parceiros confiáveis',
    'profile.yourRights': 'Seus Direitos',
    'profile.rightAccess': 'Direito de acesso aos seus dados pessoais',
    'profile.rightCorrection': 'Direito de retificação de dados incorretos',
    'profile.rightErasure': 'Direito ao esquecimento (exclusão de dados)',
    'profile.rightPortability': 'Direito à portabilidade dos dados',
    'profile.rightWithdraw': 'Direito de revogar consentimento a qualquer momento',
    'profile.accountInfo': 'Informações da Conta',
    'profile.status': 'Status',
    'profile.plan': 'Plano',
    'profile.lastUpdate': 'Última atualização',
    'profile.preferences': 'Preferências',
    'profile.preferredLanguage': 'Idioma Preferido',
    'profile.interfaceTheme': 'Tema da Interface',
    'profile.darkMode': 'Modo Escuro',
    'profile.lightMode': 'Modo Claro',
    'profile.toggleTheme': 'Alternar Tema',
    'profile.emailNotifications': 'Notificações por Email',
    'profile.newNpsResponses': 'Novas respostas NPS',
    'profile.weeklyReports': 'Relatórios semanais',
    'profile.productUpdates': 'Atualizações do produto',
    'profile.avatarTip': 'Dica para Avatar',
    'profile.avatarTipDesc': 'Use uma imagem quadrada de pelo menos 200x200px para melhor qualidade.',
    'profile.active': 'Ativo',
    'profile.professional': 'Profissional',
    
    // Settings
    'settings.generalSettings': 'Configurações Gerais',
    'settings.themeColorLabel': 'Cor do Tema',
    'settings.companyData': 'Dados da Empresa',
    'settings.companyName': 'Nome da Empresa',
    'settings.document': 'Documento (CNPJ/CPF)',
    'settings.address': 'Endereço',
    'settings.emailSettings': 'Configurações de E-mail',
    'settings.smsWhatsappSettings': 'Configurações de SMS e WhatsApp',
    'settings.smtp': 'SMTP',
    'settings.zenviaEmail': 'ZenVia E-mail',
    'settings.zenviaSms': 'ZenVia SMS',
    'settings.zenviaWhatsapp': 'ZenVia WhatsApp',
    'settings.testConnection': 'Testar Conexão',
    'settings.smtpServer': 'Servidor SMTP',
    'settings.port': 'Porta',
    'settings.username': 'Usuário',
    'settings.password': 'Senha',
    'settings.senderName': 'Nome do Remetente',
    'settings.senderEmail': 'E-mail do Remetente',
    'settings.apiKey': 'API Key',
    'settings.senderNumber': 'Número do Remetente',
    'settings.fromNumber': 'Número do Remetente',
    'settings.testEmailSent': 'Email de teste enviado com sucesso!',
    'settings.testEmailError': 'Erro ao enviar email de teste',
    'settings.testApiSuccess': 'API testada com sucesso!',
    'settings.testApiError': 'Erro ao testar API',
    'settings.emailTestSent': 'Email de Teste Enviado',
    'settings.emailTestError': 'Erro ao Enviar Email',
    'settings.zenviaTestSent': 'Mensagem de Teste ZenVia Enviada',
    'settings.zenviaTestError': 'Erro ao Enviar Mensagem de Teste',
    'settings.troubleshootingTips': 'Dicas para resolver problemas:',
    'settings.checkCredentials': 'Verifique se as credenciais estão corretas',
    'settings.checkConfiguration': 'Verifique se a configuração está correta',
    'settings.checkService': 'Verifique se o serviço está ativo na sua conta',
    'settings.phoneRequired': 'Número de telefone obrigatório no perfil',
    'settings.domainConfiguration': 'Verifique se o domínio está configurado',
    
    // Entity CRUD
    'entity.list': 'Lista',
    'entity.noItemsFound': 'Nenhum item encontrado',
    'entity.addFirstItem': 'Clique no botão acima para adicionar seu primeiro item.',
    'entity.deleteConfirm': 'Tem certeza que deseja excluir este item?',
    'entity.deleteError': 'Erro ao excluir. Tente novamente.',
    'entity.saveError': 'Erro ao salvar. Tente novamente.',
    'entity.nameRequired': 'Nome é obrigatório',
    'entity.noColor': 'Sem cor',
    'entity.enterDescription': 'Digite uma descrição',
    
    // Dashboard/Campaigns
    'campaigns.title': 'Campanhas NPS',
    'campaigns.subtitle': 'Monitore e gerencie suas campanhas NPS',
    'campaigns.newCampaign': 'Nova Campanha',
    'campaigns.noCampaigns': 'Nenhuma campanha ainda',
    'campaigns.noCampaignsDesc': 'Crie sua primeira campanha NPS para começar a coletar feedback dos clientes.',
    'campaigns.createCampaign': 'Criar Campanha',
    'campaigns.total': 'no total',
    'campaigns.campaign': 'campanha',
    'campaigns.campaigns': 'campanhas',
    'campaigns.editCampaign': 'Editar campanha',
    'campaigns.deleteCampaign': 'Excluir campanha',
    'campaigns.deleteConfirm': 'Esta ação não pode ser desfeita',
    'campaigns.deleteDescription': 'Isso excluirá permanentemente a campanha e todos os dados associados.',
    'campaigns.campaignName': 'Nome da Campanha',
    'campaigns.responses': 'respostas',
    'campaigns.response': 'resposta',
    'campaigns.created': 'Criada',
    'campaigns.whatWillBeDeleted': 'O que será excluído:',
    'campaigns.campaignConfig': 'Configuração e definições da campanha',
    'campaigns.allResponses': 'Todas as respostas da pesquisa',
    'campaigns.customFields': 'Campos personalizados do formulário e design',
    'campaigns.surveyCustomization': 'Personalização da pesquisa (cores, imagens, logo)',
    'campaigns.analyticsData': 'Todos os dados de análises e relatórios',
    'campaigns.deleteWarning': 'Tem certeza que deseja excluir',
    'campaigns.actionCannotBeUndone': 'Esta ação não pode ser desfeita e todos os dados serão perdidos permanentemente.',
    'campaigns.deleteCampaignButton': 'Excluir Campanha',
    
    // Common additional
    'common.created': 'Criado em',
    'common.total': 'Total',
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: 'pt-BR',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt-BR';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};