import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'pt-BR';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Dashboard
    'dashboard.title': 'NPS Campaigns',
    'dashboard.subtitle': 'Monitor and manage your NPS campaigns',
    'dashboard.newCampaign': 'New Campaign',
    'dashboard.noCampaigns': 'No campaigns yet',
    'dashboard.noCampaignsDesc': 'Create your first NPS campaign to start collecting customer feedback.',
    'dashboard.createCampaign': 'Create Campaign',
    
    // Campaign
    'campaign.active': 'Active',
    'campaign.inactive': 'Inactive',
    'campaign.dashboard': 'Dashboard',
    'campaign.edit': 'Edit',
    'campaign.responses': 'View Responses',
    'campaign.editForm': 'Edit Form',
    'campaign.share': 'Share Survey',
    'campaign.noResponses': 'No responses yet',
    'campaign.noResponsesDesc': 'Share your NPS survey with customers to start collecting feedback.',
    'campaign.currentNps': 'Current NPS Score',
    'campaign.npsTrend': 'NPS Trend',
    'campaign.responseDistribution': 'Response Distribution',
    'campaign.latestResponses': 'Latest Responses',
    'campaign.detractors': 'Detractors',
    'campaign.passives': 'Passives',
    'campaign.promoters': 'Promoters',
    'campaign.viewAll': 'View All',
    
    // Settings
    'settings.title': 'Settings',
    'settings.appConfig': 'App Configuration',
    'settings.dataManagement': 'Data Management',
    'settings.themeColor': 'Theme Color',
    'settings.logoUrl': 'Logo URL (Optional)',
    'settings.defaultEmail': 'Default Email',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.sources': 'Sources',
    'settings.situations': 'Situations',
    'settings.groups': 'Groups',
    'settings.sourcesDesc': 'Manage sources where customer feedback comes from',
    'settings.situationsDesc': 'Manage possible statuses for NPS responses',
    'settings.groupsDesc': 'Manage customer groups for segmentation',
    'settings.saveSettings': 'Save Settings',
    'settings.saved': 'Settings saved successfully',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.back': 'Back',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.color': 'Color',
    'common.actions': 'Actions',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.confirm': 'Confirm',
    'common.warning': 'Warning',
    
    // Login
    'login.title': 'NPS Master',
    'login.subtitle': 'Sign in to your account',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.signIn': 'Sign in',
    'login.demo': 'For demo purposes, enter any email and password',
    
    // Survey
    'survey.notFound': 'Survey Not Found',
    'survey.notFoundDesc': 'This survey may have been removed or is no longer active.',
    'survey.thankYou': 'Thank You!',
    'survey.submitted': 'Your feedback has been submitted successfully. We appreciate your input!',
    'survey.notLikely': 'Not likely at all',
    'survey.extremelyLikely': 'Extremely likely',
    'survey.submitFeedback': 'Submit Feedback',
    
    // Overview
    'overview.title': 'General Dashboard',
    'overview.subtitle': 'Overview of all NPS campaigns',
    'overview.totalCampaigns': 'Total Campaigns',
    'overview.averageNps': 'Average NPS',
    'overview.totalResponses': 'Total Responses',
    'overview.promoters': 'Promoters',
    'overview.activeCampaigns': 'active',
    'overview.allCampaigns': 'All campaigns',
    'overview.responses': 'responses',
    'overview.ofTotal': 'of total',
    'overview.generalNps': 'General NPS',
    'overview.generalDistribution': 'General Distribution',
    'overview.activeCampaignsTitle': 'Active Campaigns',
    'overview.viewAll': 'View All',
    'overview.noCampaigns': 'No campaigns found',
    'overview.noCampaignsDesc': 'Create your first NPS campaign to start collecting feedback.',
    'overview.createFirstCampaign': 'Create First Campaign',
    'overview.basedOn': 'Based on',
    'overview.campaignsText': 'campaigns',
    'overview.growing': 'Growing',
    'overview.declining': 'Declining',
    'overview.stable': 'Stable',
    'overview.active': 'Active',
    'overview.inactive': 'Inactive',
    'overview.view': 'View',
    'overview.viewAllCampaigns': 'View all',
    
    // Reports
    'reports.title': 'NPS Reports',
    'reports.subtitle': 'Detailed analysis of NPS campaign performance',
    'reports.update': 'Update',
    'reports.exportReport': 'Export Report',
    'reports.campaigns': 'Campaigns',
    'reports.period': 'Period',
    'reports.filtersApplied': 'Applied Filters',
    'reports.applyFilters': 'Apply Filters',
    'reports.clearFilters': 'Clear Filters',
    'reports.last7Days': 'Last 7 days',
    'reports.last30Days': 'Last 30 days',
    'reports.last90Days': 'Last 90 days',
    'reports.lastYear': 'Last year',
    'reports.selectCampaigns': 'Select campaigns to generate report',
    'reports.selectCampaignsDesc': 'Choose one or more campaigns in the filters above to view NPS data.',
    'reports.npsTrend': 'NPS Trend',
    'reports.responseDistribution': 'Response Distribution',
    'reports.responsesBySource': 'Responses by Source',
    'reports.campaignComparison': 'Campaign Comparison',
    'reports.responsesByDay': 'Responses by Day',
    'reports.scoreDistribution': 'Score Distribution',
    'reports.campaign': 'Campaign',
    'reports.responses': 'Responses',
    'reports.nps': 'NPS',
    'reports.neutrals': 'Neutrals',
    'reports.detractors': 'Detractors',
    'reports.insufficientData': 'Insufficient data to show trend',
    'reports.collectMoreData': 'Collect more responses over time',
    'reports.dailyResponseVolume': 'Daily Response Volume',
    'reports.responsesByScore': 'Number of Responses by Score',
    'reports.npsOverTime': 'NPS Over Time',
    
    // Contacts
    'contacts.title': 'Contacts',
    'contacts.subtitle': 'Manage your contacts and organize by groups',
    'contacts.importExcel': 'Import Excel',
    'contacts.export': 'Export',
    'contacts.newContact': 'New Contact',
    'contacts.search': 'Search by name, email, phone or company...',
    'contacts.filters': 'Filters',
    'contacts.filterByGroup': 'Filter by Group',
    'contacts.filterByTags': 'Filter by Tags',
    'contacts.allGroups': 'All groups',
    'contacts.totalContacts': 'Total Contacts',
    'contacts.filteredContacts': 'Filtered Contacts',
    'contacts.activeGroups': 'Active Groups',
    'contacts.uniqueTags': 'Unique Tags',
    'contacts.withCompany': 'With Company',
    'contacts.noContacts': 'No contacts yet',
    'contacts.noContactsDesc': 'Add your first contact to start organizing your network.',
    'contacts.noContactsFound': 'No contacts found',
    'contacts.noContactsFoundDesc': 'Try adjusting the filters to find the contacts you are looking for.',
    'contacts.addFirstContact': 'Add First Contact',
    'contacts.editContact': 'Edit Contact',
    'contacts.newContactTitle': 'New Contact',
    'contacts.name': 'Name',
    'contacts.email': 'Email',
    'contacts.phone': 'Phone',
    'contacts.company': 'Company',
    'contacts.position': 'Position',
    'contacts.groups': 'Groups',
    'contacts.tags': 'Tags',
    'contacts.notes': 'Notes',
    'contacts.addTag': 'Add tag...',
    'contacts.add': 'Add',
    'contacts.addNotesPlaceholder': 'Add notes about this contact...',
    'contacts.createdOn': 'Created on',
    'contacts.showing': 'Showing',
    'contacts.to': 'to',
    'contacts.of': 'of',
    'contacts.contactsText': 'contacts',
    'contacts.previous': 'Previous',
    'contacts.next': 'Next',
    'contacts.importContacts': 'Import Contacts from Excel',
    'contacts.downloadTemplate': 'Download Template',
    'contacts.importInstructions': 'Import Instructions',
    'contacts.csvFormat': 'File must be in CSV format (comma separated)',
    'contacts.acceptedColumns': 'Accepted columns: Name, Email, Phone, Company, Position, Tags, Notes',
    'contacts.requiredFields': 'Name, Email and Phone are required',
    'contacts.tagsSeparator': 'Tags must be separated by semicolon (;)',
    'contacts.downloadTemplateDesc': 'Download the template to see the correct format',
    'contacts.selectCsvFile': 'Select CSV File',
    'contacts.clickToSelect': 'Click to select a CSV file or drag here',
    'contacts.fileSelected': 'File selected:',
    'contacts.importError': 'Import Error',
    'contacts.importCompleted': 'Import Completed',
    'contacts.processing': 'Processing...',
    'contacts.importingContacts': 'Importing contacts, please wait...',
    'contacts.preview': 'Preview (first 5 rows)',
    'contacts.importContactsButton': 'Import Contacts',
    
    // Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your personal information and preferences',
    'profile.editProfile': 'Edit Profile',
    'profile.saveChanges': 'Save Changes',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.phone': 'Phone',
    'profile.company': 'Company',
    'profile.position': 'Position',
    'profile.memberSince': 'Member since',
    'profile.passwordSecurity': 'Password and Security',
    'profile.changePassword': 'Change Password',
    'profile.changePasswordDesc': 'Update your password to keep your account secure',
    'profile.exportData': 'Export My Data',
    'profile.exportDataDesc': 'Download a copy of all your personal data',
    'profile.deleteAccount': 'Delete My Account',
    'profile.deleteAccountDesc': 'Permanently delete your account and all your data',
    'profile.privacyProtection': 'Privacy and Data Protection',
    'profile.lgpdGdpr': 'LGPD and GDPR',
    'profile.complianceDesc': 'We comply with Brazil\'s General Data Protection Law (LGPD) and the European Union\'s General Data Protection Regulation (GDPR).',
    'profile.privacyRights': 'Your Privacy Rights',
    'profile.marketingConsent': 'I accept to receive marketing communications and news',
    'profile.analyticsConsent': 'I accept the use of data for analysis and service improvements',
    'profile.thirdPartyConsent': 'I accept data sharing with trusted partners',
    'profile.yourRights': 'Your Rights',
    'profile.rightAccess': 'Right to access your personal data',
    'profile.rightCorrection': 'Right to correct incorrect data',
    'profile.rightErasure': 'Right to be forgotten (data deletion)',
    'profile.rightPortability': 'Right to data portability',
    'profile.rightWithdraw': 'Right to withdraw consent at any time',
    'profile.accountInfo': 'Account Information',
    'profile.status': 'Status',
    'profile.plan': 'Plan',
    'profile.lastUpdate': 'Last update',
    'profile.preferences': 'Preferences',
    'profile.preferredLanguage': 'Preferred Language',
    'profile.interfaceTheme': 'Interface Theme',
    'profile.darkMode': 'Dark Mode',
    'profile.lightMode': 'Light Mode',
    'profile.toggleTheme': 'Toggle Theme',
    'profile.emailNotifications': 'Email Notifications',
    'profile.newNpsResponses': 'New NPS responses',
    'profile.weeklyReports': 'Weekly reports',
    'profile.productUpdates': 'Product updates',
    'profile.avatarTip': 'Avatar Tip',
    'profile.avatarTipDesc': 'Use a square image of at least 200x200px for better quality.',
    'profile.active': 'Active',
    'profile.professional': 'Professional',
    
    // Common additional
    'common.created': 'Created on',
    'common.total': 'Total',
  },
  'pt-BR': {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',
    
    // Dashboard
    'dashboard.title': 'Campanhas NPS',
    'dashboard.subtitle': 'Monitore e gerencie suas campanhas NPS',
    'dashboard.newCampaign': 'Nova Campanha',
    'dashboard.noCampaigns': 'Nenhuma campanha ainda',
    'dashboard.noCampaignsDesc': 'Crie sua primeira campanha NPS para começar a coletar feedback dos clientes.',
    'dashboard.createCampaign': 'Criar Campanha',
    
    // Campaign
    'campaign.active': 'Ativa',
    'campaign.inactive': 'Inativa',
    'campaign.dashboard': 'Dashboard',
    'campaign.edit': 'Editar',
    'campaign.responses': 'Ver Respostas',
    'campaign.editForm': 'Editar Formulário',
    'campaign.share': 'Compartilhar Pesquisa',
    'campaign.noResponses': 'Nenhuma resposta ainda',
    'campaign.noResponsesDesc': 'Compartilhe sua pesquisa NPS com clientes para começar a coletar feedback.',
    'campaign.currentNps': 'Pontuação NPS Atual',
    'campaign.npsTrend': 'Tendência NPS',
    'campaign.responseDistribution': 'Distribuição de Respostas',
    'campaign.latestResponses': 'Últimas Respostas',
    'campaign.detractors': 'Detratores',
    'campaign.passives': 'Neutros',
    'campaign.promoters': 'Promotores',
    'campaign.viewAll': 'Ver Todos',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.appConfig': 'Configuração do App',
    'settings.dataManagement': 'Gerenciamento de Dados',
    'settings.themeColor': 'Cor do Tema',
    'settings.logoUrl': 'URL do Logo (Opcional)',
    'settings.defaultEmail': 'Email Padrão',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.light': 'Claro',
    'settings.dark': 'Escuro',
    'settings.sources': 'Fontes',
    'settings.situations': 'Situações',
    'settings.groups': 'Grupos',
    'settings.sourcesDesc': 'Gerencie fontes de onde vem o feedback dos clientes',
    'settings.situationsDesc': 'Gerencie possíveis status para respostas NPS',
    'settings.groupsDesc': 'Gerencie grupos de clientes para segmentação',
    'settings.saveSettings': 'Salvar Configurações',
    'settings.saved': 'Configurações salvas com sucesso',
    
    // Common
    'common.loading': 'Carregando...',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.add': 'Adicionar',
    'common.back': 'Voltar',
    'common.name': 'Nome',
    'common.description': 'Descrição',
    'common.color': 'Cor',
    'common.actions': 'Ações',
    'common.required': 'Obrigatório',
    'common.optional': 'Opcional',
    'common.confirm': 'Confirmar',
    'common.warning': 'Aviso',
    
    // Login
    'login.title': 'NPS Master',
    'login.subtitle': 'Entre na sua conta',
    'login.email': 'Endereço de Email',
    'login.password': 'Senha',
    'login.signIn': 'Entrar',
    'login.demo': 'Para demonstração, digite qualquer email e senha',
    
    // Survey
    'survey.notFound': 'Pesquisa Não Encontrada',
    'survey.notFoundDesc': 'Esta pesquisa pode ter sido removida ou não está mais ativa.',
    'survey.thankYou': 'Obrigado!',
    'survey.submitted': 'Seu feedback foi enviado com sucesso. Agradecemos sua contribuição!',
    'survey.notLikely': 'Nada provável',
    'survey.extremelyLikely': 'Extremamente provável',
    'survey.submitFeedback': 'Enviar Feedback',
    
    // Overview
    'overview.title': 'Dashboard Geral',
    'overview.subtitle': 'Visão geral de todas as campanhas NPS',
    'overview.totalCampaigns': 'Total de Campanhas',
    'overview.averageNps': 'NPS Médio',
    'overview.totalResponses': 'Total de Respostas',
    'overview.promoters': 'Promotores',
    'overview.activeCampaigns': 'ativas',
    'overview.allCampaigns': 'Todas as campanhas',
    'overview.responses': 'respostas',
    'overview.ofTotal': 'do total',
    'overview.generalNps': 'NPS Geral',
    'overview.generalDistribution': 'Distribuição Geral',
    'overview.activeCampaignsTitle': 'Campanhas Ativas',
    'overview.viewAll': 'Ver Todas',
    'overview.noCampaigns': 'Nenhuma campanha encontrada',
    'overview.noCampaignsDesc': 'Crie sua primeira campanha NPS para começar a coletar feedback.',
    'overview.createFirstCampaign': 'Criar Primeira Campanha',
    'overview.basedOn': 'Baseado em',
    'overview.campaignsText': 'campanhas',
    'overview.growing': 'Crescendo',
    'overview.declining': 'Declinando',
    'overview.stable': 'Estável',
    'overview.active': 'Ativa',
    'overview.inactive': 'Inativa',
    'overview.view': 'Ver',
    'overview.viewAllCampaigns': 'Ver todas as',
    
    // Reports
    'reports.title': 'Relatórios NPS',
    'reports.subtitle': 'Análise detalhada do desempenho das campanhas NPS',
    'reports.update': 'Atualizar',
    'reports.exportReport': 'Exportar Relatório',
    'reports.campaigns': 'Campanhas',
    'reports.period': 'Período',
    'reports.filtersApplied': 'Filtros Aplicados',
    'reports.applyFilters': 'Aplicar Filtros',
    'reports.clearFilters': 'Limpar Filtros',
    'reports.last7Days': 'Últimos 7 dias',
    'reports.last30Days': 'Últimos 30 dias',
    'reports.last90Days': 'Últimos 90 dias',
    'reports.lastYear': 'Último ano',
    'reports.selectCampaigns': 'Selecione campanhas para gerar relatório',
    'reports.selectCampaignsDesc': 'Escolha uma ou mais campanhas nos filtros acima para visualizar os dados de NPS.',
    'reports.npsTrend': 'Tendência NPS',
    'reports.responseDistribution': 'Distribuição de Respostas',
    'reports.responsesBySource': 'Respostas por Fonte',
    'reports.campaignComparison': 'Comparação de Campanhas',
    'reports.responsesByDay': 'Respostas por Dia',
    'reports.scoreDistribution': 'Distribuição por Pontuação',
    'reports.campaign': 'Campanha',
    'reports.responses': 'Respostas',
    'reports.nps': 'NPS',
    'reports.neutrals': 'Neutros',
    'reports.detractors': 'Detratores',
    'reports.insufficientData': 'Dados insuficientes para mostrar tendência',
    'reports.collectMoreData': 'Colete mais respostas ao longo do tempo',
    'reports.dailyResponseVolume': 'Volume de Respostas Diárias',
    'reports.responsesByScore': 'Número de Respostas por Pontuação',
    'reports.npsOverTime': 'NPS ao Longo do Tempo',
    
    // Contacts
    'contacts.title': 'Contatos',
    'contacts.subtitle': 'Gerencie seus contatos e organize por grupos',
    'contacts.importExcel': 'Importar Excel',
    'contacts.export': 'Exportar',
    'contacts.newContact': 'Novo Contato',
    'contacts.search': 'Buscar por nome, email, telefone ou empresa...',
    'contacts.filters': 'Filtros',
    'contacts.filterByGroup': 'Filtrar por Grupo',
    'contacts.filterByTags': 'Filtrar por Tags',
    'contacts.allGroups': 'Todos os grupos',
    'contacts.totalContacts': 'Total de Contatos',
    'contacts.filteredContacts': 'Contatos Filtrados',
    'contacts.activeGroups': 'Grupos Ativos',
    'contacts.uniqueTags': 'Tags Únicas',
    'contacts.withCompany': 'Com Empresa',
    'contacts.noContacts': 'Nenhum contato ainda',
    'contacts.noContactsDesc': 'Adicione seu primeiro contato para começar a organizar sua rede.',
    'contacts.noContactsFound': 'Nenhum contato encontrado',
    'contacts.noContactsFoundDesc': 'Tente ajustar os filtros para encontrar os contatos que procura.',
    'contacts.addFirstContact': 'Adicionar Primeiro Contato',
    'contacts.editContact': 'Editar Contato',
    'contacts.newContactTitle': 'Novo Contato',
    'contacts.name': 'Nome',
    'contacts.email': 'Email',
    'contacts.phone': 'Telefone',
    'contacts.company': 'Empresa',
    'contacts.position': 'Cargo',
    'contacts.groups': 'Grupos',
    'contacts.tags': 'Tags',
    'contacts.notes': 'Notas',
    'contacts.addTag': 'Adicionar tag...',
    'contacts.add': 'Adicionar',
    'contacts.addNotesPlaceholder': 'Adicione notas sobre este contato...',
    'contacts.createdOn': 'Criado em',
    'contacts.showing': 'Mostrando',
    'contacts.to': 'a',
    'contacts.of': 'de',
    'contacts.contactsText': 'contatos',
    'contacts.previous': 'Anterior',
    'contacts.next': 'Próxima',
    'contacts.importContacts': 'Importar Contatos do Excel',
    'contacts.downloadTemplate': 'Baixar Template',
    'contacts.importInstructions': 'Instruções para Importação',
    'contacts.csvFormat': 'O arquivo deve estar no formato CSV (separado por vírgulas)',
    'contacts.acceptedColumns': 'Colunas aceitas: Nome, Email, Telefone, Empresa, Cargo, Tags, Notas',
    'contacts.requiredFields': 'Nome, Email e Telefone são obrigatórios',
    'contacts.tagsSeparator': 'Tags devem ser separadas por ponto e vírgula (;)',
    'contacts.downloadTemplateDesc': 'Baixe o template para ver o formato correto',
    'contacts.selectCsvFile': 'Selecionar Arquivo CSV',
    'contacts.clickToSelect': 'Clique para selecionar um arquivo CSV ou arraste aqui',
    'contacts.fileSelected': 'Arquivo selecionado:',
    'contacts.importError': 'Erro na Importação',
    'contacts.importCompleted': 'Importação Concluída',
    'contacts.processing': 'Processando...',
    'contacts.importingContacts': 'Importando contatos, aguarde...',
    'contacts.preview': 'Pré-visualização (primeiras 5 linhas)',
    'contacts.importContactsButton': 'Importar Contatos',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.subtitle': 'Gerencie suas informações pessoais e preferências',
    'profile.editProfile': 'Editar Perfil',
    'profile.saveChanges': 'Salvar Alterações',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.fullName': 'Nome Completo',
    'profile.phone': 'Telefone',
    'profile.company': 'Empresa',
    'profile.position': 'Cargo',
    'profile.memberSince': 'Membro desde',
    'profile.passwordSecurity': 'Senha e Segurança',
    'profile.changePassword': 'Alterar Senha',
    'profile.changePasswordDesc': 'Atualize sua senha para manter sua conta segura',
    'profile.exportData': 'Exportar Meus Dados',
    'profile.exportDataDesc': 'Baixe uma cópia de todos os seus dados pessoais',
    'profile.deleteAccount': 'Excluir Minha Conta',
    'profile.deleteAccountDesc': 'Exclua permanentemente sua conta e todos os seus dados',
    'profile.privacyProtection': 'Privacidade e Proteção de Dados',
    'profile.lgpdGdpr': 'LGPD e GDPR',
    'profile.complianceDesc': 'Estamos em conformidade com a Lei Geral de Proteção de Dados (LGPD) do Brasil e o Regulamento Geral de Proteção de Dados (GDPR) da União Europeia.',
    'profile.privacyRights': 'Seus Direitos de Privacidade',
    'profile.marketingConsent': 'Aceito receber comunicações de marketing e novidades',
    'profile.analyticsConsent': 'Aceito o uso de dados para análises e melhorias do serviço',
    'profile.thirdPartyConsent': 'Aceito o compartilhamento de dados com parceiros confiáveis',
    'profile.yourRights': 'Seus Direitos',
    'profile.rightAccess': 'Direito de acesso aos seus dados pessoais',
    'profile.rightCorrection': 'Direito de retificação de dados incorretos',
    'profile.rightErasure': 'Direito ao esquecimento (exclusão de dados)',
    'profile.rightPortability': 'Direito à portabilidade dos dados',
    'profile.rightWithdraw': 'Direito de revogar consentimento a qualquer momento',
    'profile.accountInfo': 'Informações da Conta',
    'profile.status': 'Status',
    'profile.plan': 'Plano',
    'profile.lastUpdate': 'Última atualização',
    'profile.preferences': 'Preferências',
    'profile.preferredLanguage': 'Idioma Preferido',
    'profile.interfaceTheme': 'Tema da Interface',
    'profile.darkMode': 'Modo Escuro',
    'profile.lightMode': 'Modo Claro',
    'profile.toggleTheme': 'Alternar Tema',
    'profile.emailNotifications': 'Notificações por Email',
    'profile.newNpsResponses': 'Novas respostas NPS',
    'profile.weeklyReports': 'Relatórios semanais',
    'profile.productUpdates': 'Atualizações do produto',
    'profile.avatarTip': 'Dica para Avatar',
    'profile.avatarTipDesc': 'Use uma imagem quadrada de pelo menos 200x200px para melhor qualidade.',
    'profile.active': 'Ativo',
    'profile.professional': 'Profissional',
    
    // Common additional
    'common.created': 'Criado em',
    'common.total': 'Total',
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: 'pt-BR',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt-BR';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};